/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chc.eletrica8.janelas;

import chc.eletrica8.calculos.AtualizaDados;
import chc.eletrica8.controle.DesktopPane;
import chc.eletrica8.controle.Ids;
import chc.eletrica8.entidades.Carga;
import chc.eletrica8.enums.Ligacao;
import chc.eletrica8.enums.UnidadePotencia;
import chc.eletrica8.enums.Usabilidade;
import chc.eletrica8.servico.CargaService;
import chc.eletrica8.servico.CircuitoService;
import chc.eletrica8.servico.ProjetoService;
import chc.eletrica8.servico.tableModel.CargaTableModel;
import chc.eletrica8.uteis.ApenasNumero;
import chc.eletrica8.uteis.Numero;
import chc.eletrica8.uteis.TrataID;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class CargaFrm extends javax.swing.JInternalFrame implements KeyListener {

    //private GenericTableModel tabelaModelo;
    private CargaTableModel tabelaModeloCarga;
    private Carga carga;

    /**
     * Creates new form ProjetoFrm
     */
    public CargaFrm() {
        initComponents();
        this.iniciaTabelaCargas("");
        this.eventoSelecaoTabela();
        this.adicionarKeyListener();
        this.cbUsabilidadeItens();
        this.cbLigacaoItens();
        this.cbUnidades();
        Ids.setIdCarga(0);
        Ids.imprimiIds();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        campoFd = new javax.swing.JTextField();
        campoFutil = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoSimutaneidade = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        campoRendimento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbLigacao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        campoLocal = new javax.swing.JTextField();
        campoQuantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDescricao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoFServico = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoNPolos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoPerdas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        campoPotencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbUnidade = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        campoFPotencia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        campoComprimento = new javax.swing.JTextField();
        lblAtualizacao = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tabelaEquipamento = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Carga");
        setMinimumSize(new java.awt.Dimension(129, 50));
        setName("ProjetoFrm"); // NOI18N
        setPreferredSize(new java.awt.Dimension(675, 700));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvar.setIconTextGap(2);
        btnSalvar.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnSalvar.setMaximumSize(new java.awt.Dimension(71, 32));
        btnSalvar.setMinimumSize(new java.awt.Dimension(71, 32));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExcluir.setIconTextGap(2);
        btnExcluir.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCopiar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnCopiar.setText("Copiar");
        btnCopiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCopiar.setIconTextGap(2);
        btnCopiar.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnCopiar.setMaximumSize(new java.awt.Dimension(71, 32));
        btnCopiar.setMinimumSize(new java.awt.Dimension(71, 32));
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNovo.setIconTextGap(2);
        btnNovo.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnNovo.setMaximumSize(new java.awt.Dimension(71, 32));
        btnNovo.setMinimumSize(new java.awt.Dimension(71, 32));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnRelatorios.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnRelatorios.setText("Relatórios");
        btnRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRelatorios.setIconTextGap(2);
        btnRelatorios.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnRelatorios.setMaximumSize(new java.awt.Dimension(71, 32));
        btnRelatorios.setMinimumSize(new java.awt.Dimension(71, 32));
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        painelBotoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCopiar, btnExcluir, btnNovo, btnRelatorios, btnSalvar});

        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir)
                    .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel10.setText("Fator de demanda:");

        campoFd.setName("campoFd"); // NOI18N

        campoFutil.setName("campoFutil"); // NOI18N

        jLabel11.setText("Fator de utilização:");

        jLabel15.setText("Fator de simutâneidade:");

        jLabel3.setText("Tipo:");

        campoSimutaneidade.setName("campoSimutaneidade"); // NOI18N

        jLabel17.setText("Rendimento:");

        campoRendimento.setName("campoRendimento"); // NOI18N

        jLabel8.setText("Ligação:");

        jLabel2.setText("Local:");

        campoQuantidade.setName("campoQuantidade"); // NOI18N

        jLabel5.setText("Quantidade:");

        textoDescricao.setColumns(20);
        textoDescricao.setRows(5);
        textoDescricao.setName(""); // NOI18N
        jScrollPane1.setViewportView(textoDescricao);

        jLabel4.setText("Descrição:");

        jLabel12.setText("Fator de serviço:");

        campoFServico.setName("campoFServico"); // NOI18N

        campoNome.setName("campoNome"); // NOI18N

        jLabel13.setText("Nome:");

        jLabel6.setText("N° pólos:");

        campoNPolos.setName("campoNPolos"); // NOI18N

        jLabel14.setText("Perdas Reator (W):");

        campoPerdas.setName("campoPerdas"); // NOI18N

        jLabel18.setText("Potência:");

        campoPotencia.setName("campoPotencia"); // NOI18N

        jLabel9.setText("Unidade:");

        jLabel19.setText("Fator de potência:");

        campoFPotencia.setName("campoFPotencia"); // NOI18N

        jLabel20.setText("Distância de instalação:");

        campoComprimento.setName("campoComprimento"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFutil)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoFServico, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 5, Short.MAX_VALUE))
                            .addComponent(campoFd)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSimutaneidade))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNome)
                            .addComponent(cbLigacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel2)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoComprimento)
                            .addComponent(campoFPotencia)
                            .addComponent(campoLocal, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(jLabel9)
                            .addComponent(jLabel17)
                            .addComponent(jLabel4))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoRendimento)
                            .addComponent(cbUnidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoPotencia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoPerdas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoNPolos, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(55, 55, 55)
                        .addComponent(campoQuantidade))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoQuantidade)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoPotencia)
                        .addComponent(jLabel18))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbLigacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNome)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFd)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFServico)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFutil)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNPolos)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoPerdas)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoRendimento)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoSimutaneidade)
                            .addComponent(jLabel15)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoFPotencia)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoLocal)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoComprimento)
                            .addComponent(jLabel20))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel15, jLabel17, jLabel2, jLabel5});

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jScrollPane14.setViewportView(tabelaEquipamento);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane14)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1734, 1734, 1734))
        );

        setBounds(0, 0, 665, 511);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Carga carga = null;

        if (Ids.getIdCarga() == 0 && Ids.getIdCircuito() == 0) {
            carga = getDados();
            carga.setCircuito(null);
            CargaService.salva(carga);
        } else if (Ids.getIdCarga() == 0 && Ids.getIdCircuito() > 0) {
            carga = getDados();

            for (int i = 1; i <= carga.getQuantidade(); i++) {
                Carga cargaQuant = new Carga();
                cargaQuant = getDados();
                cargaQuant.setQuantidade(1);
                cargaQuant.setCircuito(CircuitoService.getById(Ids.getIdCircuito()));
                cargaQuant.getCircuito().getCargas().add(cargaQuant);
                AtualizaDados.carga(cargaQuant);
            }

            carga = new Carga();
            carga = getDados();
            carga.setQuantidade(1);
            carga.setCircuito(null);
            CargaService.salva(carga);

        } else if (Ids.getIdCarga() > 0 && Ids.getIdCircuito() > 0) {
            carga = getDados();
            if (carga.getCircuito() == null) {

                for (int i = 1; i <= carga.getQuantidade(); i++) {
                    Carga cargaQuant = new Carga();
                    cargaQuant = getDados();
                    cargaQuant.setQuantidade(1);
                    cargaQuant.setCircuito(CircuitoService.getById(Ids.getIdCircuito()));
                    cargaQuant.getCircuito().getCargas().add(cargaQuant);
                    AtualizaDados.carga(cargaQuant);
                }

                carga = new Carga();
                Ids.setIdCarga(0);
                carga = getDados();
                carga.setQuantidade(1);
                carga.setCircuito(null);
                CargaService.salva(carga);

            } else {
                if (carga.getQuantidade() > 1) {
                    for (int i = 1; i <= carga.getQuantidade(); i++) {
                        Carga q = CargaService.getById(Ids.getIdCarga()).clonarSemID();
                        q.setQuantidade(1);
                        AtualizaDados.carga(q);

                    }

                    CargaService.removeById(Ids.getIdCarga());
                }else{
                    AtualizaDados.carga(CargaService.getById(Ids.getIdCarga()));
                }

                
            }

        } else if (Ids.getIdCarga() > 0 && Ids.getIdCircuito() == 0) {
            carga = getDados();
            carga.setCircuito(null);
            CargaService.salva(carga);
        }

        this.iniciaTabelaCargas("Salva");
        this.apagaDadosFrm();
        Ids.setIdCarga(0);
        Ids.imprimiIds();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //ProjetoService.salva(ProjetoService.getById(1));
        CargaService.removeById(Ids.getIdCarga());

        this.iniciaTabelaCargas("Exclui");
        this.apagaDadosFrm();
        Ids.setIdCarga(0);
        Ids.imprimiIds();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        Carga q = CargaService.getById(Ids.getIdCarga()).clonarSemID();
        CargaService.salva(q);

        this.iniciaTabelaCargas("Copia");
        this.apagaDadosFrm();
        Ids.setIdCarga(0);
        Ids.imprimiIds();
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.iniciaTabelaCargas("Novo");
        this.apagaDadosFrm();
        Ids.setIdCarga(0);
        Ids.imprimiIds();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (Ids.getIdCircuito() != 0) {
            CircuitoFrm frm = new CircuitoFrm();
            DesktopPane.desktop.add(frm);
            frm.setVisible(true);
            Ids.setIdCarga(0);
            Ids.imprimiIds();
        }

    }//GEN-LAST:event_formInternalFrameClosing

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed

    }//GEN-LAST:event_btnRelatoriosActionPerformed

    /**
     * @return the lblAtualizacao
     */
    public javax.swing.JLabel getLblAtualizacao() {
        return lblAtualizacao;
    }

    private void cbUsabilidadeItens() {
        cbTipo.removeAllItems();
        cbTipo.addItem(null);
        for (Usabilidade usa : Usabilidade.getLista()) {
            cbTipo.addItem(usa);

        }
    }

    private void cbLigacaoItens() {
        cbLigacao.removeAllItems();
        cbLigacao.addItem(null);
        for (Ligacao usa : Ligacao.getLista()) {
            cbLigacao.addItem(usa);
        }
        cbLigacao.setSelectedIndex(1);
    }

    private void cbUnidades() {
        cbUnidade.removeAllItems();
        cbUnidade.addItem(null);
        for (UnidadePotencia usa : UnidadePotencia.getLista()) {
            cbUnidade.addItem(usa);
        }
        cbUnidade.setSelectedIndex(5);
    }

    private void eventoSelecaoTabela() {
        tabelaEquipamento.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evt) {
                if (Ids.getIdCircuito() == 0) {
                    lblAtualizacao.setText("Atualização");
                }
                if (getLblAtualizacao().getText().equals("Novo com cópia")) {
                    getLblAtualizacao().setText("Novo");
                }
                int linha = tabelaEquipamento.getSelectedRow();
                if (evt.getValueIsAdjusting() == true && linha > -1) {
                    Carga carga = (Carga) tabelaModeloCarga.getCarga(linha);
                    setDados(carga);
                    Ids.setIdCarga(carga.getId());
                    Ids.imprimiIds();
                }
            }
        }
        );
    }

    private void adicionarKeyListener() {
        this.campoFd.addKeyListener(this);
        this.campoFutil.addKeyListener(this);
        this.campoSimutaneidade.addKeyListener(this);
        this.campoFServico.addKeyListener(this);
        this.campoQuantidade.addKeyListener(this);
        this.campoRendimento.addKeyListener(this);
        this.campoComprimento.addKeyListener(this);
        this.campoFPotencia.addKeyListener(this);
        this.campoNPolos.addKeyListener(this);
        this.campoPerdas.addKeyListener(this);
    }

    public void iniciaTabelaCargas(String dica) {
        List<Carga> lista = new ArrayList<>();
        if (Ids.getIdCircuito() == 0 || dica.equals("Novo")) {
            lista = CargaService.getByExpres("from Carga where circuito = null", null);
        } else if (dica.equals("Copia") || dica.equals("Exclui") || dica.equals("Salva") || dica.equals("")) {
            lista = CargaService.getByExpres("from Carga where circuito = :ID", new Object[]{"ID", CircuitoService.getById(Ids.getIdCircuito())});
        }
        if (!lista.isEmpty()) {
            tabelaModeloCarga = new CargaTableModel(lista);
            tabelaEquipamento.setModel(tabelaModeloCarga);
        } else {
            DefaultTableModel model = new DefaultTableModel();
            this.tabelaEquipamento.setModel(model);
        }
        Ids.imprimiIds();
    }

    private Carga getDados() {
        Carga carga;
        if (Ids.getIdCarga() > 0) {
            carga = CargaService.getById(TrataID.IntegerToInteger(Ids.getIdCarga()));

        } else {
            carga = new Carga();
        }

        carga.setFd(Numero.stringToDouble(this.campoFd.getText(), 1));
        carga.setFu(Numero.stringToDouble(this.campoFutil.getText(), 1));
        carga.setLocalizacao(this.campoLocal.getText());
        carga.setDescricao(this.textoDescricao.getText());
        carga.setUsabilidade((Usabilidade) cbTipo.getModel().getSelectedItem());
        carga.setQuantidade(Numero.stringToInteger(campoQuantidade.getText(), 1));
        carga.setRendimento(Numero.stringToDouble(this.campoRendimento.getText(), 1));
        carga.setfSimu(Numero.stringToDouble(this.campoSimutaneidade.getText(), 1));
        carga.setFs(Numero.stringToDouble(this.campoFServico.getText(), 1));
        carga.setLigacao((Ligacao) cbLigacao.getModel().getSelectedItem());
        carga.setNome(this.campoNome.getText());
        carga.setnPolos(Numero.stringToInteger(campoNPolos.getText(), 1));
        carga.setPerdasReator(Numero.stringToDouble(this.campoPerdas.getText(), 1));
        carga.setPotencia(Numero.stringToDouble(this.campoPotencia.getText(), 1));
        carga.setRendimento(Numero.stringToDouble(this.campoRendimento.getText(), 1));
        carga.setFp(Numero.stringToDouble(this.campoFPotencia.getText(), 1));
        carga.setUnidade((UnidadePotencia) cbUnidade.getModel().getSelectedItem());
        carga.setComprimentoInstal(Numero.stringToDouble(this.campoComprimento.getText(), 0));

        return carga;
    }

    public void apagaDadosFrm() {
        this.campoFd.setText("");
        this.campoFutil.setText("");
        this.campoLocal.setText("");
        this.textoDescricao.setText("");
        this.cbTipo.setSelectedIndex(-1);
        this.cbLigacao.setSelectedIndex(-1);
        this.campoQuantidade.setText("");
        this.campoSimutaneidade.setText("");
        this.campoFServico.setText("");
        this.campoRendimento.setText("");
        this.campoNome.setText("");
        this.campoNPolos.setText("");
        this.campoPerdas.setText("");
        this.campoFPotencia.setText("");
        this.cbUnidade.setSelectedIndex(-1);
        this.campoPotencia.setText("");
        this.campoComprimento.setText("");
        Ids.imprimiIds();
    }

    public void setDados(Carga carga) {
        if (carga != null) {
            this.campoFd.setText(Numero.decimal(carga.getFd(), "##.##"));
            this.campoFutil.setText(Numero.decimal(carga.getFu(), "##.##"));
            this.campoLocal.setText(carga.getLocalizacao());
            this.textoDescricao.setText(carga.getDescricao());
            this.cbTipo.getModel().setSelectedItem(carga.getUsabilidade());
            this.cbLigacao.getModel().setSelectedItem(carga.getLigacao());
            this.campoQuantidade.setText(Integer.toString(carga.getQuantidade()));
            this.campoSimutaneidade.setText(Numero.decimal(carga.getfSimu(), "##.##"));
            this.campoFServico.setText(Numero.decimal(carga.getFs(), "##.##"));
            this.campoRendimento.setText(Numero.decimal(carga.getRendimento(), "##.##"));
            this.campoNome.setText(carga.getNome());
            this.campoNPolos.setText(Integer.toString(carga.getnPolos()));
            this.campoPerdas.setText(Numero.decimal(carga.getPerdasReator(), "##.##"));
            this.campoFPotencia.setText(Numero.decimal(carga.getFp(), "##.##"));
            this.cbUnidade.getModel().setSelectedItem(carga.getUnidade());
            this.campoPotencia.setText(Numero.decimal(carga.getPotencia(), "##.##"));
            this.campoComprimento.setText(Numero.decimal(carga.getComprimentoInstal(), "##.##"));
            Ids.imprimiIds();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField campoComprimento;
    private javax.swing.JTextField campoFPotencia;
    private javax.swing.JTextField campoFServico;
    private javax.swing.JTextField campoFd;
    private javax.swing.JTextField campoFutil;
    private javax.swing.JTextField campoLocal;
    private javax.swing.JTextField campoNPolos;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPerdas;
    private javax.swing.JTextField campoPotencia;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JTextField campoRendimento;
    private javax.swing.JTextField campoSimutaneidade;
    private javax.swing.JComboBox<Ligacao> cbLigacao;
    private javax.swing.JComboBox<Usabilidade> cbTipo;
    private javax.swing.JComboBox<UnidadePotencia> cbUnidade;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JLabel lblAtualizacao;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JTable tabelaEquipamento;
    private javax.swing.JTextArea textoDescricao;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        ApenasNumero.campo(e, "campoFd");
        ApenasNumero.campo(e, "campoFutil");
        ApenasNumero.campo(e, "campoRendimento");
        ApenasNumero.campo(e, "campoSimutaneidade");
        ApenasNumero.campo(e, "campoQuantidade");
        ApenasNumero.campo(e, "campoFServico");
        ApenasNumero.campo(e, "campoComprimento");
        ApenasNumero.campo(e, "campoFPotencia");
        ApenasNumero.campo(e, "campoNPolos");
        ApenasNumero.campo(e, "campoPerdas");
    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {

    }
}
