/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chc.eletrica8.janelas;


import chc.eletrica8.controle.Ids;
import chc.eletrica8.entidades.Concessionaria;
import chc.eletrica8.entidades.RamalLigacao;
import chc.eletrica8.enums.BitolasMili;
import chc.eletrica8.enums.DiametroPolegadas;
import chc.eletrica8.enums.DisjuntorTermoMag;
import chc.eletrica8.enums.MetodoCalculo;
import chc.eletrica8.enums.TiposCondutores;
import chc.eletrica8.enums.TiposFornecimento;
import chc.eletrica8.servico.ConcessionariaService;
import chc.eletrica8.servico.RamalLigacaoService;
import chc.eletrica8.servico.tableModel.GenericTableModel;
import chc.eletrica8.uteis.ApenasNumero;
import chc.eletrica8.uteis.Numero;
import chc.eletrica8.uteis.TrataID;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public final class ConcessionariasFrm extends javax.swing.JInternalFrame implements KeyListener {

    private static final long serialVersionUID = 1L;

    private GenericTableModel tabelaModelo;

    /**
     * Creates new form ProjetoFrm
     */
    public ConcessionariasFrm() {
        initComponents();
        iniciaTabelaConcessionarias();
        this.eventoSelecaoTabela();
        adicionarKeyListener();
        cbMetodoCalculoItens();
        cbTiposFornecimentoItens();
        cbTipoCondutorItens();
        cbFaseMinimaItens();
        cbNeutroMinimoItens();
        cbDiametroEletroAcoGalvaItens();
        cbDiametroEletroAcoGalvaAterramentoItens();
        cbDisjuntorTermoMagItens();
        cbCondutorAterramentoItens();
        cbBitolaItens();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();
        lblIdFonte = new javax.swing.JLabel();
        scrollEsquerdo = new javax.swing.JScrollPane();
        painelEsquerdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoTensao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbMetodoCalculo = new javax.swing.JComboBox<>();
        cbTiposFornecimento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        campoCarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoLocal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbdisjuntorTermoMag = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cbFaseMinima = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        cbNeutroMinimo = new javax.swing.JComboBox<>();
        painelDireito = new javax.swing.JPanel();
        scrollDireito = new javax.swing.JScrollPane();
        tabelaConcessionaria = new javax.swing.JTable();
        scrollEsquerdo1 = new javax.swing.JScrollPane();
        painelEsquerdo1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cbTipoCondutor = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbBitola = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        campoDistanciaOrla = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cbMaterial = new javax.swing.JComboBox<>();
        scrollEsquerdo2 = new javax.swing.JScrollPane();
        painelEsquerdo2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        cbDiametroEletroAcoGalva = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        cbDiametroEletroAcoGalvaEnterrado = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        cbCondutorAterramento = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Concessionaria");
        setName("ProjetoFrm"); // NOI18N

        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvar.setIconTextGap(2);
        btnSalvar.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnSalvar.setMaximumSize(new java.awt.Dimension(71, 32));
        btnSalvar.setMinimumSize(new java.awt.Dimension(71, 32));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExcluir.setIconTextGap(2);
        btnExcluir.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCopiar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnCopiar.setText("Copiar");
        btnCopiar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCopiar.setIconTextGap(2);
        btnCopiar.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnCopiar.setMaximumSize(new java.awt.Dimension(71, 32));
        btnCopiar.setMinimumSize(new java.awt.Dimension(71, 32));
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIdFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir)
                            .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblIdFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        scrollEsquerdo.setBorder(null);
        scrollEsquerdo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        painelEsquerdo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelEsquerdo.setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel1.setText("Nome:");

        jLabel2.setText("Tensão nominal F-N (V):");

        campoTensao.setName("campoTensao"); // NOI18N

        jLabel4.setText("Tipo de fornecimento:");

        jLabel5.setText("Método de cálculo:");

        jLabel3.setText("Carga (KW):");

        campoCarga.setName("campoCarga"); // NOI18N

        jLabel7.setText("Local:");

        jLabel18.setText("Disjuntor termo-magnético (A):");

        jLabel27.setText("Fase mínima de cobre isolado (mm²):");

        jLabel28.setText("Neutro mínima de cobre isolado (mm²):");

        javax.swing.GroupLayout painelEsquerdoLayout = new javax.swing.GroupLayout(painelEsquerdo);
        painelEsquerdo.setLayout(painelEsquerdoLayout);
        painelEsquerdoLayout.setHorizontalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNome)
                            .addComponent(campoTensao)
                            .addComponent(campoLocal)
                            .addComponent(campoCarga)
                            .addComponent(cbMetodoCalculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTiposFornecimento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEsquerdoLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(24, 24, 24)
                        .addComponent(cbdisjuntorTermoMag, 0, 132, Short.MAX_VALUE))
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(24, 24, 24)
                        .addComponent(cbFaseMinima, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(24, 24, 24)
                        .addComponent(cbNeutroMinimo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelEsquerdoLayout.setVerticalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbMetodoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTiposFornecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbdisjuntorTermoMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cbFaseMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cbNeutroMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        scrollEsquerdo.setViewportView(painelEsquerdo);

        painelDireito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        painelDireito.setPreferredSize(new java.awt.Dimension(172, 22));

        scrollDireito.setBorder(null);

        tabelaConcessionaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaConcessionaria.setName("tabelaConcessionaria"); // NOI18N
        tabelaConcessionaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConcessionariaMouseClicked(evt);
            }
        });
        scrollDireito.setViewportView(tabelaConcessionaria);

        javax.swing.GroupLayout painelDireitoLayout = new javax.swing.GroupLayout(painelDireito);
        painelDireito.setLayout(painelDireitoLayout);
        painelDireitoLayout.setHorizontalGroup(
            painelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollDireito)
        );
        painelDireitoLayout.setVerticalGroup(
            painelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollDireito, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );

        scrollEsquerdo1.setBorder(null);
        scrollEsquerdo1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        painelEsquerdo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ramal de ligação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelEsquerdo1.setPreferredSize(new java.awt.Dimension(300, 150));

        jLabel20.setText("Tipo de condutor:");

        jLabel21.setText("Bitola (mm²):");

        jLabel6.setText("Distância para Orla marítima (m):");

        campoDistanciaOrla.setName("campoDistanciaOrla"); // NOI18N

        jLabel22.setText("Material utilizado:");

        cbMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cobre", "Alumínio" }));

        javax.swing.GroupLayout painelEsquerdo1Layout = new javax.swing.GroupLayout(painelEsquerdo1);
        painelEsquerdo1.setLayout(painelEsquerdo1Layout);
        painelEsquerdo1Layout.setHorizontalGroup(
            painelEsquerdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEsquerdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEsquerdo1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(cbTipoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelEsquerdo1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(cbBitola, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEsquerdo1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(campoDistanciaOrla))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEsquerdo1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(cbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelEsquerdo1Layout.setVerticalGroup(
            painelEsquerdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEsquerdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbTipoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cbBitola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(painelEsquerdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoDistanciaOrla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        scrollEsquerdo1.setViewportView(painelEsquerdo1);

        scrollEsquerdo2.setBorder(null);
        scrollEsquerdo2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        painelEsquerdo2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        painelEsquerdo2.setPreferredSize(new java.awt.Dimension(300, 150));

        jLabel29.setText("Diâmetro do eletroduto de aço galva (pol): ");

        jLabel30.setText("Diâmetro do eletroduto de aterramento (pol): ");

        jLabel31.setText("Condutor de aterramento (mm²)");

        javax.swing.GroupLayout painelEsquerdo2Layout = new javax.swing.GroupLayout(painelEsquerdo2);
        painelEsquerdo2.setLayout(painelEsquerdo2Layout);
        painelEsquerdo2Layout.setHorizontalGroup(
            painelEsquerdo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEsquerdo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEsquerdo2Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(24, 24, 24)
                        .addComponent(cbDiametroEletroAcoGalva, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelEsquerdo2Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(24, 24, 24)
                        .addComponent(cbDiametroEletroAcoGalvaEnterrado, 0, 102, Short.MAX_VALUE))
                    .addGroup(painelEsquerdo2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(24, 24, 24)
                        .addComponent(cbCondutorAterramento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelEsquerdo2Layout.setVerticalGroup(
            painelEsquerdo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEsquerdo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cbDiametroEletroAcoGalva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cbDiametroEletroAcoGalvaEnterrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cbCondutorAterramento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        scrollEsquerdo2.setViewportView(painelEsquerdo2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDireito, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollEsquerdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollEsquerdo2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollEsquerdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollEsquerdo2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDireito, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 942, 587);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Concessionaria concessionaria = this.getDados();
        ConcessionariaService.salva(concessionaria);
        this.apagaDadosFrm();
        this.iniciaTabelaConcessionarias();
        //Ids.idConcessionaria = 0;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ConcessionariaService.removeById(Ids.getIdConcessionaria());
        this.iniciaTabelaConcessionarias();
        this.apagaDadosFrm();
        Ids.setIdConcessionaria((Integer) 0);
        Ids.setIdRamalLigacao((Integer) 0);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        Concessionaria concessionaria = ConcessionariaService.getById(Ids.getIdConcessionaria()).clonarSemID();
        ConcessionariaService.salva(concessionaria);

        this.iniciaTabelaConcessionarias();
        this.apagaDadosFrm();
        Ids.setIdConcessionaria((Integer) 0);
        Ids.setIdRamalLigacao((Integer) 0);
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void tabelaConcessionariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConcessionariaMouseClicked
        if (evt.getClickCount() == 1) {

        }
        if (evt.getClickCount() == 2) {

        }
    }//GEN-LAST:event_tabelaConcessionariaMouseClicked

    private void adicionarKeyListener() {
        campoTensao.addKeyListener(this);
        campoDistanciaOrla.addKeyListener(this);
    }

    private void cbMetodoCalculoItens() {
        cbMetodoCalculo.removeAllItems();
        cbMetodoCalculo.addItem(null);
        for (MetodoCalculo usa : MetodoCalculo.getLista()) {
            cbMetodoCalculo.addItem(usa);
        }
    }

    private void cbTiposFornecimentoItens() {
        cbTiposFornecimento.removeAllItems();
        cbTiposFornecimento.addItem(null);
        for (TiposFornecimento usa : TiposFornecimento.getLista()) {
            cbTiposFornecimento.addItem(usa);
        }
    }

    private void cbDisjuntorTermoMagItens() {
        cbdisjuntorTermoMag.removeAllItems();
        cbdisjuntorTermoMag.addItem(null);
        for (DisjuntorTermoMag usa : DisjuntorTermoMag.getLista()) {
            cbdisjuntorTermoMag.addItem(usa);
        }
    }

    private void cbTipoCondutorItens() {
        cbTipoCondutor.removeAllItems();
        cbTipoCondutor.addItem(null);
        for (TiposCondutores usa : TiposCondutores.getLista()) {
            cbTipoCondutor.addItem(usa);
        }
    }

    private void cbFaseMinimaItens() {
        cbFaseMinima.removeAllItems();
        cbFaseMinima.addItem(null);
        for (BitolasMili usa : BitolasMili.getLista()) {
            cbFaseMinima.addItem(usa);
        }
    }

    private void cbNeutroMinimoItens() {
        cbNeutroMinimo.removeAllItems();
        cbNeutroMinimo.addItem(null);
        for (BitolasMili usa : BitolasMili.getLista()) {
            cbNeutroMinimo.addItem(usa);
        }
    }

    private void cbDiametroEletroAcoGalvaItens() {
        cbDiametroEletroAcoGalva.removeAllItems();
        cbDiametroEletroAcoGalva.addItem(null);
        for (DiametroPolegadas usa : DiametroPolegadas.getLista()) {
            cbDiametroEletroAcoGalva.addItem(usa);
        }
    }

    private void cbDiametroEletroAcoGalvaAterramentoItens() {
        cbDiametroEletroAcoGalvaEnterrado.removeAllItems();
        cbDiametroEletroAcoGalvaEnterrado.addItem(null);
        for (DiametroPolegadas usa : DiametroPolegadas.getLista()) {
            cbDiametroEletroAcoGalvaEnterrado.addItem(usa);
        }
    }

    private void cbCondutorAterramentoItens() {
        cbCondutorAterramento.removeAllItems();
        cbCondutorAterramento.addItem(null);
        for (BitolasMili usa : BitolasMili.getLista()) {
            cbCondutorAterramento.addItem(usa);
        }
    }

    private void cbBitolaItens() {
        cbBitola.removeAllItems();
        cbBitola.addItem(null);
        for (BitolasMili usa : BitolasMili.getLista()) {
            cbBitola.addItem(usa);
        }
    }

    private void eventoSelecaoTabela() {
        tabelaConcessionaria.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent evt) {
                int linha = tabelaConcessionaria.getSelectedRow();
                if (evt.getValueIsAdjusting() == true && linha > -1) {
                    Concessionaria concessionaria = (Concessionaria) tabelaModelo.loadItem(linha);
                    setDados(concessionaria);
                    Ids.setIdRamalLigacao(concessionaria.getRamalLigacao().getId());
                    Ids.setIdConcessionaria(concessionaria.getId());
                }
            }
        }
        );
    }

    public void iniciaTabelaConcessionarias() {
        //Verificar porque não posso usar List<Concessionaria> lista = ProjetoService.getById(Ids.idProjeto).getConcessionarias(); 
        //A tabelaConcessionaria não atualiza a última inclusão como de a Entidade anterior não atualizasse.
        List<Concessionaria> todos = ConcessionariaService.getAll();

        if (!todos.isEmpty()) {
            tabelaModelo = new GenericTableModel(todos, Concessionaria.class);
            tabelaConcessionaria.setModel(tabelaModelo);
        } else {
            DefaultTableModel model = new DefaultTableModel();
            this.tabelaConcessionaria.setModel(model);
        }
    }

    private Concessionaria getDados() {
        Concessionaria concessionaria;
        RamalLigacao ramalLigacao;
        if (Ids.getIdConcessionaria() > 0) {
            concessionaria = ConcessionariaService.getById(Ids.getIdConcessionaria());
        } else {
            concessionaria = new Concessionaria();
        }
        if (Ids.getIdRamalLigacao() > 0) {
            ramalLigacao = RamalLigacaoService.getById(Ids.getIdRamalLigacao());
        } else {
            ramalLigacao = new RamalLigacao();
        }
        concessionaria.setId(TrataID.IntegerToInteger(Ids.getIdConcessionaria()));
        concessionaria.setCarga(this.campoCarga.getText());
        concessionaria.setNome(this.campoNome.getText());
        concessionaria.setLocalizacao(this.campoLocal.getText());
        concessionaria.setMetodoCalculo((MetodoCalculo) cbMetodoCalculo.getModel().getSelectedItem());
        concessionaria.setTiposFornecimento((TiposFornecimento) cbTiposFornecimento.getModel().getSelectedItem());
        concessionaria.setDisjuntorTermoMag((DisjuntorTermoMag) cbdisjuntorTermoMag.getModel().getSelectedItem());
        concessionaria.setTipoCondutor((TiposCondutores) cbTipoCondutor.getModel().getSelectedItem());
        concessionaria.setFaseMinimaCobreIsolado((BitolasMili) cbFaseMinima.getModel().getSelectedItem());
        concessionaria.setNeutroMinimoCobreIsolado((BitolasMili) cbNeutroMinimo.getModel().getSelectedItem());
        concessionaria.setDiametroEletroAcoGalva((DiametroPolegadas) cbDiametroEletroAcoGalva.getModel().getSelectedItem());
        concessionaria.setDiametroEletroAterramento((DiametroPolegadas) cbDiametroEletroAcoGalvaEnterrado.getModel().getSelectedItem());
        concessionaria.setTensaoFN(Numero.stringToDouble(campoTensao.getText(), 0));
        concessionaria.setCondutorAterramentoAco((BitolasMili) cbCondutorAterramento.getModel().getSelectedItem());
        ramalLigacao.setBitola((BitolasMili) cbBitola.getModel().getSelectedItem());
        ramalLigacao.setCondutor((TiposCondutores) cbTipoCondutor.getModel().getSelectedItem());
        ramalLigacao.setMaterial((String) cbMaterial.getModel().getSelectedItem());
        ramalLigacao.setDistanciaOrla(campoDistanciaOrla.getText());
        RamalLigacaoService.salva(ramalLigacao);
        concessionaria.setRamalLigacao(ramalLigacao);
        return concessionaria;
    }

    public void apagaDadosFrm() {

        Ids.setIdConcessionaria((Integer) 0);
        Ids.setIdRamalLigacao((Integer) 0);
        this.campoCarga.setText("");
        this.campoNome.setText("");
        this.campoLocal.setText("");
        this.campoTensao.setText("");
        cbMetodoCalculo.setSelectedIndex(-1);
        cbTiposFornecimento.setSelectedIndex(-1);
        cbdisjuntorTermoMag.setSelectedIndex(-1);
        cbTipoCondutor.setSelectedIndex(-1);
        cbFaseMinima.setSelectedIndex(-1);
        cbNeutroMinimo.setSelectedIndex(-1);
        cbDiametroEletroAcoGalva.setSelectedIndex(-1);
        cbDiametroEletroAcoGalvaEnterrado.setSelectedIndex(-1);
        cbCondutorAterramento.setSelectedIndex(-1);
        cbBitola.setSelectedIndex(-1);
        cbMaterial.setSelectedIndex(-1);
        cbTipoCondutor.setSelectedIndex(-1);
        campoDistanciaOrla.setText("");
    }

    public void setDados(Concessionaria concessionaria) {
        if (concessionaria != null) {
            Ids.setIdConcessionaria(concessionaria.getId());
            this.campoCarga.setText(concessionaria.getCarga());
            this.campoNome.setText(concessionaria.getNome());
            this.campoLocal.setText(concessionaria.getLocalizacao());
            this.campoTensao.setText(Numero.decimal(concessionaria.getTensaoFN(), "##.##"));
            cbMetodoCalculo.getModel().setSelectedItem(concessionaria.getMetodoCalculo());
            cbTiposFornecimento.getModel().setSelectedItem(concessionaria.getTiposFornecimento());
            cbdisjuntorTermoMag.getModel().setSelectedItem(concessionaria.getDisjuntorTermoMag());
            cbTipoCondutor.getModel().setSelectedItem(concessionaria.getTipoCondutor());
            cbFaseMinima.getModel().setSelectedItem(concessionaria.getFaseMinimaCobreIsolado());
            cbNeutroMinimo.getModel().setSelectedItem(concessionaria.getNeutroMinimoCobreIsolado());
            cbDiametroEletroAcoGalva.getModel().setSelectedItem(concessionaria.getDiametroEletroAcoGalva());
            cbDiametroEletroAcoGalvaEnterrado.getModel().setSelectedItem(concessionaria.getDiametroEletroAterramento());
            cbCondutorAterramento.getModel().setSelectedItem(concessionaria.getCondutorAterramentoAco());
            cbBitola.getModel().setSelectedItem(concessionaria.getRamalLigacao().getBitola());
            cbMaterial.getModel().setSelectedItem(concessionaria.getRamalLigacao().getMaterial());
            cbTipoCondutor.getModel().setSelectedItem(concessionaria.getRamalLigacao().getCondutor());
            campoDistanciaOrla.setText(concessionaria.getRamalLigacao().getDistanciaOrla());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField campoCarga;
    private javax.swing.JTextField campoDistanciaOrla;
    private javax.swing.JTextField campoLocal;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTensao;
    private javax.swing.JComboBox<BitolasMili> cbBitola;
    private javax.swing.JComboBox<BitolasMili> cbCondutorAterramento;
    private javax.swing.JComboBox<DiametroPolegadas> cbDiametroEletroAcoGalva;
    private javax.swing.JComboBox<DiametroPolegadas> cbDiametroEletroAcoGalvaEnterrado;
    private javax.swing.JComboBox<BitolasMili> cbFaseMinima;
    private javax.swing.JComboBox<String> cbMaterial;
    private javax.swing.JComboBox<MetodoCalculo> cbMetodoCalculo;
    private javax.swing.JComboBox<BitolasMili> cbNeutroMinimo;
    private javax.swing.JComboBox<TiposCondutores> cbTipoCondutor;
    private javax.swing.JComboBox<TiposFornecimento> cbTiposFornecimento;
    private javax.swing.JComboBox<DisjuntorTermoMag> cbdisjuntorTermoMag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblIdFonte;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelDireito;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JPanel painelEsquerdo1;
    private javax.swing.JPanel painelEsquerdo2;
    private javax.swing.JScrollPane scrollDireito;
    private javax.swing.JScrollPane scrollEsquerdo;
    private javax.swing.JScrollPane scrollEsquerdo1;
    private javax.swing.JScrollPane scrollEsquerdo2;
    private javax.swing.JTable tabelaConcessionaria;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        ApenasNumero.campo(e, "campoTensao");
        ApenasNumero.campo(e, "campoDistanciaOrla");

    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {

    }
}
